# https://cloud.google.com/appengine/docs/standard/go/config/appref?hl=ko
runtime: go115  # or another supported version
env_variables: 
  BOOTPAY_APP_ID: 62b45e0fe38c3000215aec6e
  BOOTPAY_PK: jx87N78iC8uIGjGtflQvbvF/5U2PzlQsaFKMvjm91uo=
  GOOGLE_APPLICATION_CREDENTIALS: config/secret/io-box-firebase-adminsdk-sbwq0-ce3f0de117.json
  GOOGLE_CLOUD_PROJECT: io-box